version: '3.7'
services:
  url-shortener:
    #image:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    env_file: ./.env
    depends_on:
      - mysql
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: "${MYSQL_DB_DATABASE}"
      RDS_USERNAME: "${MYSQL_DB_USER}"
      RDS_PASSWORD: "${MYSQL_DB_PASSWORD}"
    networks:
      - url-shortener-network

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_DB_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_DB_USER}"
      MYSQL_PASSWORD: "${MYSQL_DB_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB_DATABASE}"
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - url-shortener-network

# Volumes
volumes:
  mysql-database-data-volume:

networks:
  url-shortener-network: